### ISSUE TITLE
Support for batched masks?

### ISSUE THREAD

**Issue by liusida** [BadCafeCode/masquerade-nodes-comfyui#30]
When I tried to use "Cut By Mask" to apply the "batch_masks" output from "SAMDetector (segmented)" node to the original image

![image](https://github.com/BadCafeCode/masquerade-nodes-comfyui/assets/14249458/fa0f11c5-1d03-4895-83e9-04d8f144de3c)

This error occurs:
```
Error occurred when executing Cut By Mask:

The expanded size of the tensor (1) must match the existing size (6) at non-singleton dimension 0. Target sizes: [1, 3121, 4820]. Tensor sizes: [6, 3121, 4820]

File "/mnt/data/ComfyUI-debug/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/mnt/data/ComfyUI-debug/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/mnt/data/ComfyUI-debug/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/mnt/data/ComfyUI-debug/custom_nodes/masquerade-nodes-comfyui/MaskNodes.py", line 754, in cut
alpha_mask[:,:,:,3] = mask
~~~~~~~~~~^^^^^^^^^
```

I went to the code and found there are several issues of getting the values of `is_empty`, `use_width`, `use_height` correctly for batched masks. (`is_empty` is all True, `use_width` and `use_height` is 1 instead of a value for each mask.) I'm not familiar with the code base, so I'll just report the issue here.

Thanks.

Also related:
https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/622

**Comment by ltdrdata** [comment]
For the benefit of others, processing can be done using nodes that convert between Batch and List.

https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/622#issuecomment-2143675219
