### ISSUE TITLE
 Looking for a node to create simple horizontal and vertical masks

### ISSUE THREAD

**Issue by andreszs** [BadCafeCode/masquerade-nodes-comfyui#38]
I'm looking for a node with the ability to **create simple masked areas** of arbitrary size, if possible with a visual representation of the areas, similar to this **Visual Area Prompt** node:
![image](https://github.com/user-attachments/assets/7f084b45-0e73-4633-8ccc-cfad919340d0)

The only thing I've found so far is the awkward method using the **Simple Binary Pattern** from ComfyRoll Studio:
![image](https://github.com/user-attachments/assets/4f94d654-6207-49a7-a56b-a4911cb64f1d)

However it cannot create vertical masks, in fact it creates only images, then we have to convert it to mask, and I'd prefer to avoid installing a plethora of nodes to use just 1 of them.

Can this extension create simple masked areas like this? If yes, which nodes are involved? Thanks in advance.

_PS. I'm asking this here because the author has disabled the [GitHub Discussions](https://docs.github.com/en/discussions) section for this repo._

**Comment by guill** [comment]
Hey @andreszs! While the [Create Rect Mask](https://github.com/BadCafeCode/masquerade-nodes-comfyui?tab=readme-ov-file#create-rect-mask) node will do what you want, the output *will* be a black and white image which you have to convert to a mask via the `Image to Mask` node.

Some example config:
```
# Vertical stripe
mode = percent
width = 20
height = 100

# Horizontal stripe
mode = percent
width = 100
height = 20
```

This node pack doesn't have any front-end components though (which is what would be required to display a preview).

**Comment by andreszs** [comment]
Thanks @guill, I've put together some nodes that output **MASK** with embedded preview, they are now part of the [Impact Pack](https://github.com/ltdrdata/ComfyUI-Impact-Pack/pull/861#event-15718013435) if anyone is interested. The same nodes (without preview) have been merged into [WAS Node Suite](https://github.com/WASasquatch/was-node-suite-comfyui/pull/526) too.
